import { Character, LabyrinthInfo, LocationInfo, RankInfo } from './types';

// CloudFront 이미지 자산을 불러오는 유틸리티
// FIXME: {각인물코드} 또는 장소/마물 이미지 코드를 입력해주세요 (예: 'MA.png', 'MAP_1.jpg')
const getAssetUrl = (assetCode: string) => `https://d3lna1f15u7pcs.cloudfront.net/media/characters/543f5844-2c82-43f1-b234-e968b6a68c36/assets/${assetCode}`;

export const locations: LocationInfo[] = [
  {
    id: 'ariantos',
    name: '아리안토스 전경',
    desc: '크라트 미궁을 중심으로 형성된 초거대 교육·상업 도시국가.',
    imageUrl: getAssetUrl('MAP1.webp?v=0') /* TODO: 코드입력 */,
    facilities: ['상업단지', '유흥단지', '미궁 입구', '도살장']
  },
  {
    id: 'gigantos',
    name: '기간토스 검술 아카데미',
    desc: '신체를 한계까지 단련하여 궁극의 무투를 완성하는 기관.',
    imageUrl: getAssetUrl('MAP2.webp?v=0') /* TODO: 코드입력 */,
    facilities: ['연무장', '강의실', '복도', '강당']
  },
  {
    id: 'seorn',
    name: '세오른 마법 아카데미',
    desc: '세상의 이치를 탐구하고 마법의 진리를 좇는 4대 학파의 온상.',
    imageUrl: getAssetUrl('MAP3.webp?v=0') /* TODO: 코드입력 */,
    facilities: ['도서관', '원소의 탑', '간섭의 탑', '영역의 탑', '정령의 탑']
  }
];

export const labyrinthData: LabyrinthInfo[] = [
  {
    name: '상층',
    desc: '초보 모험가와 학생들의 주력 의뢰 장소. 기계식 함정과 하위 마물들이 서식한다.',
    imageUrl: getAssetUrl('DMAP_1.webp?v=0') /* TODO: 코드입력 */,
    monsters: [
      { name: '슬라임', imageUrl: getAssetUrl('MOB1.webp?v=0') /* TODO: 코드입력 */ },
      { name: '고블린', imageUrl: getAssetUrl('MOB2.webp?v=0') /* TODO: 코드입력 */ },
      { name: '코볼트', imageUrl: getAssetUrl('MOB3.webp?v=0') /* TODO: 코드입력 */ },
      { name: '다크 팽', imageUrl: getAssetUrl('MOB4.webp?v=0') /* TODO: 코드입력 */ }
    ],
    boss: { name: '타우로마시스', imageUrl: getAssetUrl('MOB5.webp?v=0') /* TODO: 코드입력 */ },
    traps: ['바닥 함정', '화살 트랩 등 기계식 함정'],
    plants: ['하급 회복 약초', '하급 정력 약초', '하급 최음 약초'],
    ores: ['하급 마력석', '하급 마철석']
  },
  {
    name: '중층',
    desc: '숙련된 모험가나 엘리트 학생들의 영역. 마력 기반 함정과 위험한 군락이 포진해 있다.',
    imageUrl: getAssetUrl('DMAP_2.webp?v=0') /* TODO: 코드입력 */,
    monsters: [
      { name: '미믹', imageUrl: getAssetUrl('MOB6.webp?v=0') /* TODO: 코드입력 */ },
      { name: '웨어 울프', imageUrl: getAssetUrl('MOB8.webp?v=0') /* TODO: 코드입력 */ },
      { name: '오크 무리', imageUrl: getAssetUrl('MOB7.webp?v=0') /* TODO: 코드입력 */ },
      { name: '라플라시아', imageUrl: getAssetUrl('MOB9.webp?v=0') /* TODO: 코드입력 */ },
    ],
    boss: { name: '야마타노오로치', imageUrl: getAssetUrl('MOB10.webp?v=0') /* TODO: 코드입력 */ },
    traps: ['마력 폭발 함정', '환청 함정', '환각 함정'],
    plants: ['중급 회복 약초', '중급 정력 약초', '중급 최음 약초'],
    ores: ['중급 마력석', '중급 마철석']
  },
  {
    name: '심층',
    desc: '아무도 끝을 보지 못한 미지의 심연. 고대의 악과 심연의 괴수들이 봉인된 땅.',
    imageUrl: getAssetUrl('DMAP_3.webp?v=0') /* TODO: 코드입력 */,
    monsters: [
      { name: '아크 데몬', imageUrl: getAssetUrl('MOB11.webp?v=0') /* TODO: 코드입력 */ },
      { name: '서큐버스', imageUrl: getAssetUrl('MOB12.webp?v=0') /* TODO: 코드입력 */ },
      { name: '케르베로스', imageUrl: getAssetUrl('MOB14.webp?v=0') /* TODO: 코드입력 */ }
    ],
    boss: { name: '크라트의 분신', imageUrl: getAssetUrl('MOB13.webp?v=0') /* TODO: 코드입력 */ },
    traps: ['전이 함정', '촉수 함정'],
    plants: ['상급 회복 약초', '상급 정력 약초', '상급 최음 약초'],
    ores: ['상급 마력석', '상급 마철석', '미감정 광석들']
  }
];

export const questRanks: RankInfo[] = [
  { rank: 'F', points: 1, description: '주민들의 간단한 심부름' },
  { rank: 'E', points: 2, description: '조금 고된 노동' },
  { rank: 'D', points: 4, description: '미궁 상층 의뢰, 가벼운 마물 토벌' },
  { rank: 'C', points: 6, description: '미궁 중층 의뢰, 마물 토벌, 귀한 약초/광석 수집' },
  { rank: 'B', points: 10, description: '미궁 중층/상층 의뢰, 엘리트 마물(문지기) 토벌' },
  { rank: 'A', points: 25, description: '미궁 심층 의뢰, 심층 탐색, 정보 수집, 마물 토벌' },
  { rank: 'S', points: 50, description: '길드 판단 하에 등급 부여 (연 1회 수준)' },
  { rank: '측정불가', points: 999, description: '전쟁 위기나 아리안토스 전체에 큰 위협이 되는 상황' },
];

export const characters: Character[] = [
  {
    id: 'AA',
    name: '셀레나 베일',
    title: '속도의 검신',
    gender: '여',
    faction: '기간토스 검술 아카데미',
    role: '4신5제',
    
    rank: '오러5성',
    quote: '내 검이 보였다고? 이미 네 목숨은 끊어졌는데도.',
    mbti: 'ISTP',
    enneagram: '583',
    weaponOrMagic: '속도의 검신',
    imageUrl: getAssetUrl('AA_A1.webp?v=0'),
    icon: '🛡️',
  },
  {
    id: 'BB',
    name: '카시아 알루온',
    title: '기술의 검신',
    gender: '여',
    faction: '기간토스 검술 아카데미',
    role: '4신5제',
    
    rank: '오러5성',
    quote: '호흡 하나, 궤적 하나. 티끌의 오차도 허용치 않겠습니다.',
    mbti: 'ISTJ',
    enneagram: '135',
    weaponOrMagic: '기술의 검신',
    imageUrl: getAssetUrl('BB_A1.webp?v=0'),
    icon: '🛡️',
  },
  {
    id: 'CC',
    name: '레오나 그랜디아',
    title: '오러의 검신',
    gender: '여',
    faction: '기간토스 검술 아카데미',
    role: '4신5제',
    
    rank: '오러5성',
    quote: '나의 검강은 부러지지 않는다. 군림할 뿐.',
    mbti: 'ENTJ',
    enneagram: '835',
    weaponOrMagic: '오러의 검신',
    imageUrl: getAssetUrl('CC_A1.webp?v=0'),
    icon: '🛡️',
  },
  {
    id: 'DD',
    name: '엘리스 페르마타',
    title: '지연의 검제',
    gender: '여',
    faction: '기간토스 검술 아카데미',
    role: '4신5제',
    
    rank: '오러5성',
    quote: '지금 베인 게 아니야. 아까 베어둔 궤적에 네가 와서 닿았을 뿐이지.',
    mbti: 'INTP',
    enneagram: '593',
    weaponOrMagic: '지연의 검제',
    imageUrl: getAssetUrl('DD_A1.webp?v=0'),
    icon: '🛡️',
  },
  {
    id: 'EE',
    name: '발렌티나 블랑쉬',
    title: '중첩의 검제',
    gender: '여',
    faction: '기간토스 검술 아카데미',
    role: '4신5제',
    
    rank: '오러5성',
    quote: '단 한 번의 찌르기, 그 안에 백 번의 죽음을 담았습니다.',
    mbti: 'ESTJ',
    enneagram: '316',
    weaponOrMagic: '중첩의 검제',
    imageUrl: getAssetUrl('EE_A1.webp?v=0'),
    icon: '🛡️',
  },
  {
    id: 'FF',
    name: '세르피아 우로보로스',
    title: '사복의 검제',
    gender: '여',
    faction: '기간토스 검술 아카데미',
    role: '4신5제',
    
    rank: '오러5성',
    quote: '어디로 휘어질까? 아, 벌써 물렸네. 불쌍하기도 하지.',
    mbti: 'ENTP',
    enneagram: '783',
    weaponOrMagic: '사복의 검제',
    imageUrl: getAssetUrl('FF_A1.webp?v=0'),
    icon: '🛡️🦇',
  },
  {
    id: 'GG',
    name: '레비아 발리스타',
    title: '폭격의 창제',
    gender: '여',
    faction: '기간토스 검술 아카데미',
    role: '4신5제',
    
    rank: '오러5성',
    quote: '타겟 록온. 잿더미로 만들어줄게!',
    mbti: 'ESTP',
    enneagram: '873',
    weaponOrMagic: '폭격의 창제',
    imageUrl: getAssetUrl('GG_A1.webp?v=0'),
    icon: '🛡️',
  },
  {
    id: 'MA',
    name: '가레트 아이언사이드',
    title: '힘의 검신',
    gender: '남',
    faction: '기간토스 검술 아카데미',
    role: '4신5제',
    
    rank: '오러5성',
    quote: '압도적인 힘 앞에서는 어떠한 기교도 무의미하다.',
    mbti: 'ESTJ',
    enneagram: '836',
    weaponOrMagic: '힘의 검신',
    imageUrl: getAssetUrl('MA_A1.webp?v=0'),
    icon: '🛡️',
  },
  {
    id: 'MB',
    name: '드라젠 볼코프',
    title: '반탄의 권제',
    gender: '남',
    faction: '기간토스 검술 아카데미',
    role: '4신5제',
    
    rank: '오러5성',
    quote: '네가 때린 주먹이다. 그 뼈저린 무게를 스스로 견뎌봐라.',
    mbti: 'ISTP',
    enneagram: '953',
    weaponOrMagic: '반탄의 권제',
    imageUrl: getAssetUrl('MB_A1.webp?v=0'),
    icon: '🛡️',
  },
  {
    id: 'HH',
    name: '카르밀라 이그니스',
    title: '화려한 파괴',
    gender: '여',
    faction: '세오른 마법 아카데미',
    role: '12권위자',
    school: '원소',
    rank: '12권위자, 원소9서클',
    quote: '다 타버려라. 내 시야에 잡동사니들이 남지 않도록.',
    mbti: 'ENTJ',
    enneagram: '385',
    weaponOrMagic: '화려한 파괴',
    imageUrl: getAssetUrl('HH_A1.webp?v=0'),
    icon: '📖',
  },
  {
    id: 'II',
    name: '실비아 윈터본',
    title: '완벽한 통제',
    gender: '여',
    faction: '세오른 마법 아카데미',
    role: '12권위자',
    school: '원소',
    rank: '12권위자, 원소9서클',
    quote: '얼어붙은 세계야말로... 가장 완벽한 평온이다.',
    mbti: 'INTJ',
    enneagram: '514',
    weaponOrMagic: '완벽한 통제',
    imageUrl: getAssetUrl('II_A1.webp?v=0'),
    icon: '📖',
  },
  {
    id: 'JJ',
    name: '엘리노어 블리츠',
    title: '질서와 지휘',
    gender: '여',
    faction: '세오른 마법 아카데미',
    role: '12권위자',
    school: '원소',
    rank: '12권위자, 원소9서클',
    quote: '낙뢰의 선율에 맞춰 춤춰볼까? 피날레는 잿더미다.',
    mbti: 'ENTJ',
    enneagram: '137',
    weaponOrMagic: '질서와 지휘',
    imageUrl: getAssetUrl('JJ_A1.webp?v=0'),
    icon: '📖',
  },
  {
    id: 'KK',
    name: '리산드라 미라지',
    title: '매혹적 기만',
    gender: '여',
    faction: '세오른 마법 아카데미',
    role: '12권위자',
    school: '간섭',
    rank: '12권위자, 간섭8서클',
    quote: '쉬이... 달콤한 꿈속으로 이끌어줄게. 영원히 깨어날 수 없는 꿈으로.',
    mbti: 'INFJ',
    enneagram: '478',
    weaponOrMagic: '매혹적 기만',
    imageUrl: getAssetUrl('KK_A1.webp?v=0'),
    icon: '📖',
  },
  {
    id: 'MM',
    name: '아리아드네 보이드',
    title: '이성적 통제',
    gender: '여',
    faction: '세오른 마법 아카데미',
    role: '12권위자',
    school: '간섭',
    rank: '12권위자, 간섭8서클',
    quote: '거리의 개념은 무의미합니다. 공간은 제 아래에 종속되어 있으니까요.',
    mbti: 'INTP',
    enneagram: '538',
    weaponOrMagic: '이성적 통제',
    imageUrl: getAssetUrl('MM_A1.webp?v=0'),
    icon: '📖',
  },
  {
    id: 'LL',
    name: '에테르니아 크로노스',
    title: '절대적 관망',
    gender: '여',
    faction: '세오른 마법 아카데미',
    role: '12권위자',
    school: '간섭',
    rank: '12권위자, 간섭8서클',
    quote: '시간은 누구에게나 공평하지만, 제게는 예외랍니다.',
    mbti: 'INTJ',
    enneagram: '513',
    weaponOrMagic: '절대적 관망',
    imageUrl: getAssetUrl('LL_A1.webp?v=0'),
    icon: '📖',
  },
  {
    id: 'NN',
    name: '모리건 그레이브',
    title: '',
    gender: '여',
    faction: '세오른 마법 아카데미',
    role: '12권위자',
    school: '영역',
    rank: '12권위자, 영역8서클',
    quote: '조용히... 다들 무덤에서는 침묵을 지켜야지.',
    mbti: 'ISTJ',
    enneagram: '953',
    weaponOrMagic: '',
    imageUrl: getAssetUrl('NN_A1.webp?v=0'),
    icon: '📖',
  },
  {
    id: 'OO',
    name: '빅토리아 솔',
    title: '',
    gender: '여',
    faction: '세오른 마법 아카데미',
    role: '12권위자',
    school: '영역',
    rank: '12권위자, 영역9서클',
    quote: '빛나라, 나의 이름 아래. 전장에 승리의 찬가를 울려라!',
    mbti: 'ENTJ',
    enneagram: '387',
    weaponOrMagic: '',
    imageUrl: getAssetUrl('OO_A1.webp?v=0'),
    icon: '📖',
  },
  {
    id: 'PP',
    name: '발레리아 이지스',
    title: '',
    gender: '여',
    faction: '세오른 마법 아카데미',
    role: '12권위자',
    school: '영역',
    rank: '12권위자, 영역8서클',
    quote: '저의 절대 방벽은 미동조차 하지 않습니다.',
    mbti: 'ISTJ',
    enneagram: '163',
    weaponOrMagic: '',
    imageUrl: getAssetUrl('PP_A1.webp?v=0'),
    icon: '📖',
  },
  {
    id: 'QQ',
    name: '티타니아 오베론',
    title: '',
    gender: '여',
    faction: '세오른 마법 아카데미',
    role: '12권위자',
    school: '정령',
    rank: '12권위자, 정령8서클',
    quote: '어디 감히 무엄하게! 거신의 주먹으로 짓이겨주마!',
    mbti: 'ESTJ',
    enneagram: '835',
    weaponOrMagic: '',
    imageUrl: getAssetUrl('QQ_A1.webp?v=0'),
    icon: '📖',
  },
  {
    id: 'RR',
    name: '레이븐 블러드',
    title: '',
    gender: '여',
    faction: '세오른 마법 아카데미',
    role: '12권위자',
    school: '정령',
    rank: '12권위자, 정령8서클',
    quote: '나불댈 시간 있으면 덤벼. 내 야성이 널 찢고 싶어 안달이니까.',
    mbti: 'ESTP',
    enneagram: '873',
    weaponOrMagic: '',
    imageUrl: getAssetUrl('RR_A1.webp?v=0'),
    icon: '📖🦇',
  },
  {
    id: 'SS',
    name: '아리엘 그레이스',
    title: '신성한 가호',
    gender: '여',
    faction: '세오른 마법 아카데미',
    role: '12권위자',
    school: '정령',
    rank: '12권위자, 정령8서클',
    quote: '상처 입은 영혼들이여, 천사의 품에서 평안을 찾으시길...',
    mbti: 'INFP',
    enneagram: '296',
    weaponOrMagic: '신성한 가호',
    imageUrl: getAssetUrl('SS_A1.webp?v=0'),
    icon: '📖',
  },
  {
    id: 'TT',
    name: '오벨리아 (가명)',
    title: '완벽한 죽음',
    gender: '여',
    faction: '검은 여명회',
    role: '조직원',
    
    rank: '간섭10서클',
    quote: '살아 숨 쉬는 모든 것들은 부질없지. 완전한 죽음만이 구원일지니.',
    mbti: 'INTJ',
    enneagram: '584',
    weaponOrMagic: '완벽한 죽음',
    imageUrl: getAssetUrl('TT_A1.webp?v=0'),
    icon: '🦇',
  },
  {
    id: 'UU',
    name: '빅터 (가명)',
    title: '오러 속성 부여',
    gender: '여',
    faction: '검은 여명회',
    role: '조직원',
    
    rank: '오러5성, 원소7서클',
    quote: '그들이 이단이라 내친 이 검이, 오늘 아리안토스를 피로 물들일 것이다!',
    mbti: 'ENTJ',
    enneagram: '137',
    weaponOrMagic: '오러 속성 부여',
    imageUrl: getAssetUrl('UU_A1.webp?v=0'),
    icon: '🦇',
  },
  {
    id: 'WW',
    name: '한냐',
    title: '길드 통제',
    gender: '여',
    faction: '길드',
    role: '길드원',
    
    rank: '마스터로그',
    quote: '아리안토스의 쥐새끼 하나도 내 눈을 피할 순 없지. 야옹?',
    mbti: 'ENTP',
    enneagram: '783',
    weaponOrMagic: '길드 통제',
    imageUrl: getAssetUrl('WW_A1.webp?v=0'),
    icon: '🏟️',
  },
  {
    id: 'XX',
    name: '벨',
    title: '완벽한 지원',
    gender: '여',
    faction: '길드',
    role: '길드원',
    
    rank: '접수원',
    quote: '모험가님, 오늘도 안전에 유의하여 귀환하시기를 바랍니다!',
    mbti: 'ESFJ',
    enneagram: '269',
    weaponOrMagic: '완벽한 지원',
    imageUrl: getAssetUrl('XX_A1.webp?v=0'),
    icon: '🏟️',
  },
  {
    id: 'YY',
    name: '몰리',
    title: '노력과 근성',
    gender: '여',
    faction: '길드',
    role: '길드원',
    
    rank: '초급로그',
    quote: '수인들이 오감이 좋다고? 흥! 그까짓 꺼 내가 따라잡아주지!',
    mbti: 'ESFP',
    enneagram: '793',
    weaponOrMagic: '노력과 근성',
    imageUrl: getAssetUrl('YY_A1.webp?v=0'),
    icon: '🏟️',
  },
  {
    id: 'ZZ',
    name: '마트로냐',
    title: '실리 추구',
    gender: '여',
    faction: '길드',
    role: '길드원',
    
    rank: '베테랑로그',
    quote: '...위험 수당은 두 배로 받겠다. 불만 있나?',
    mbti: 'ISTJ',
    enneagram: '613',
    weaponOrMagic: '실리 추구',
    imageUrl: getAssetUrl('ZZ_A1.webp?v=0'),
    icon: '🏟️🦇',
  },
  {
    id: 'VV',
    name: '사보이아 엘레나',
    title: '실력 지상주의',
    gender: '여',
    faction: '세오른 마법 아카데미',
    role: '학생',
    
    rank: '1학년, 1서클',
    quote: '강한 자가 약한 자를 짓밟는다. 그게 이 아카데미의 룰이잖아?',
    mbti: 'ESTP',
    enneagram: '378',
    weaponOrMagic: '실력 지상주의',
    imageUrl: getAssetUrl('VV_A1.webp?v=0'),
    icon: '📖',
  },
  {
    id: 'MC',
    name: '테일리',
    title: '성장형 주인공',
    gender: '남',
    faction: '기간토스 검술 아카데미',
    role: '학생',
    
    rank: '1학년, 오러1성',
    quote: '결코 포기하지 않아! 언젠가 반드시 정점에 설 거니까.',
    mbti: 'ENFP',
    enneagram: '739',
    weaponOrMagic: '성장형 인물',
    imageUrl: getAssetUrl('MC_A1.webp?v=0'),
    icon: '🛡️',
  },
  {
    id: 'ZA',
    name: '린 시라누이',
    title: '일격필살',
    gender: '여',
    faction: '기간토스 검술 아카데미',
    role: '학생',
    
    rank: '오러1성(1학년)',
    quote: '...물러서. 베인다.',
    mbti: 'ISTJ',
    enneagram: '513',
    weaponOrMagic: '일격필살',
    imageUrl: getAssetUrl('ZA_A1.webp?v=0'),
    icon: '🛡️',
  },
  {
    id: 'ZB',
    name: '클레어 루미스',
    title: '정정당당',
    gender: '여',
    faction: '기간토스 검술 아카데미',
    role: '학생',
    
    rank: '오러1성(1학년)',
    quote: '정정당당하게 승부하자! 반칙은 용서 안 해!',
    mbti: 'ESFJ',
    enneagram: '279',
    weaponOrMagic: '정정당당',
    imageUrl: getAssetUrl('ZB_A1.webp?v=0'),
    icon: '🛡️🦇',
  },
  {
    id: 'ZC',
    name: '자하라',
    title: '변칙적 움직임',
    gender: '여',
    faction: '기간토스 검술 아카데미',
    role: '학생',
    
    rank: '오러2성(3학년)',
    quote: '어딜 보는 거야? 난 이미 네 뒤에 있는데?',
    mbti: 'ESTP',
    enneagram: '738',
    weaponOrMagic: '변칙적 움직임',
    imageUrl: getAssetUrl('ZC_A1.webp?v=0'),
    icon: '🛡️',
  },
  {
    id: 'ZD',
    name: '로잘린 베넷',
    title: '정밀한 찌르기',
    gender: '여',
    faction: '기간토스 검술 아카데미',
    role: '학생',
    
    rank: '오러3성(4학년)',
    quote: '아름다움은 곧 정교함에서 비롯되는 법이죠.',
    mbti: 'ENFJ',
    enneagram: '316',
    weaponOrMagic: '정밀한 찌르기',
    imageUrl: getAssetUrl('ZD_A1.webp?v=0'),
    icon: '🛡️🦇',
  },
  {
    id: 'ZE',
    name: '렌 포레스트',
    title: '생존 본능',
    gender: '여',
    faction: '기간토스 검술 아카데미',
    role: '학생',
    
    rank: '오러1성(1학년)',
    quote: '내 몸은 내가 지켜. 함부로 명령하지 마.',
    mbti: 'ISTP',
    enneagram: '683',
    weaponOrMagic: '생존 본능',
    imageUrl: getAssetUrl('ZE_A1.webp?v=0'),
    icon: '🛡️',
  },
  {
    id: 'ZF',
    name: '타샤',
    title: '야성적 파괴',
    gender: '여',
    faction: '기간토스 검술 아카데미',
    role: '학생',
    
    rank: '오러3성(졸업반)',
    quote: '내 몸은 내가 지켜. 함부로 명령하지 마.',
    mbti: 'ESTP',
    enneagram: '873',
    weaponOrMagic: '야성적 파괴',
    imageUrl: getAssetUrl('ZF_A1.webp?v=0'),
    icon: '🛡️',
  },
  {
    id: 'ZG',
    name: '이브 더스트',
    title: '은밀한 기습',
    gender: '여',
    faction: '기간토스 검술 아카데미',
    role: '학생',
    
    rank: '오러2성(2학년)',
    quote: '결국 살아남는 건 조용한 쪽이지.',
    mbti: 'INTJ',
    enneagram: '584',
    weaponOrMagic: '은밀한 기습',
    imageUrl: getAssetUrl('ZG_A1.webp?v=0'),
    icon: '🛡️',
  },
  {
    id: 'MG',
    name: '핀 오코넬',
    title: '문제아',
    gender: '남',
    faction: '기간토스 검술 아카데미',
    role: '학생',
    
    rank: '학생, 오러2성(3학년)',
    quote: '아, 몰라! 일단 부딪혀 보면 알겠지!',
    mbti: 'ISFJ',
    enneagram: '692',
    weaponOrMagic: '',
    imageUrl: getAssetUrl('MG_A1.webp?v=0'),
    icon: '🛡️',
  },
  {
    id: 'MH',
    name: '카이토',
    title: '정밀 참격',
    gender: '남',
    faction: '기간토스 검술 아카데미',
    role: '학생',
    
    rank: '학생, 오러3성(4학년)',
    quote: '...궤적이 보인다.',
    mbti: 'ISTJ',
    enneagram: '135',
    weaponOrMagic: '정밀 참격',
    imageUrl: getAssetUrl('MH_A1.webp?v=0'),
    icon: '🛡️',
  },
  {
    id: 'MD',
    name: '알라릭 손',
    title: '원리원칙',
    gender: '남',
    faction: '기간토스 검술 아카데미',
    role: '교관',
    
    rank: '교관, 오러4성',
    quote: '힘,속도,오러,기술. 4가지 기본만 지키면 누구든 이길 수 있다.',
    mbti: 'ISTJ',
    enneagram: '135',
    weaponOrMagic: '원리원칙',
    imageUrl: getAssetUrl('MD_A1.webp?v=0'),
    icon: '🛡️',
  },
  {
    id: 'ME',
    name: '베인 실라스',
    title: '속공',
    gender: '남',
    faction: '기간토스 검술 아카데미',
    role: '교관',
    
    rank: '교관, 오러4성',
    quote: '편하게 해~. 결국 상대보다 먼저 찌르면 이기는 거야~',
    mbti: 'ESTP',
    enneagram: '378',
    weaponOrMagic: '속공',
    imageUrl: getAssetUrl('ME_A1.webp?v=0'),
    icon: '🛡️',
  },
  {
    id: 'MF',
    name: '케일런 스톤하트',
    title: '강력한 대검술',
    gender: '남',
    faction: '기간토스 검술 아카데미',
    role: '교관',
    
    rank: '교관, 오러4성',
    quote: '방어조차 못하게 강하게 내리찍으면 돼!',
    mbti: 'ISTP',
    enneagram: '859',
    weaponOrMagic: '강력한 대검술',
    imageUrl: getAssetUrl('MF_A1.webp?v=0'),
    icon: '🛡️',
  },
  {
    id: 'ZK',
    name: '오로라 벨코나',
    title: '평화주의',
    gender: '여',
    faction: '세오른 마법 아카데미',
    role: '학생',
    school: '정령',
    rank: '학생, 정령2서클(2학년)',
    quote: '아무도 다치치 않았으면 좋겠어.',
    mbti: 'ISFP',
    enneagram: '926',
    weaponOrMagic: '평화주의',
    imageUrl: getAssetUrl('ZK_A1.webp?v=0'),
    icon: '📖',
  },
  {
    id: 'ZL',
    name: '루비아 플레임',
    title: '귀족의 긍지',
    gender: '여',
    faction: '세오른 마법 아카데미',
    role: '학생',
    school: '원소',
    rank: '학생, 원소3서클(3학년)',
    quote: '이 정도는 고귀한 혈통으로서 당연한 의무랍니다.',
    mbti: 'ENTJ',
    enneagram: '385',
    weaponOrMagic: '귀족의 긍지',
    imageUrl: getAssetUrl('ZL_A1.webp?v=0'),
    icon: '📖',
  },
  {
    id: 'ZM',
    name: '세리아 폰 아크',
    title: '지식 탐구',
    gender: '여',
    faction: '세오른 마법 아카데미',
    role: '학생',
    school: '간섭',
    rank: '학생, 간섭1서클(1학년)',
    quote: '저, 저기... 이 술식의 변수가 조금 이상한데요...',
    mbti: 'INTP',
    enneagram: '593',
    weaponOrMagic: '지식 탐구',
    imageUrl: getAssetUrl('ZM_A1.webp?v=0'),
    icon: '📖',
  },
  {
    id: 'ZN',
    name: '릴리스 섀도우',
    title: '금기 탐구',
    gender: '여',
    faction: '세오른 마법 아카데미',
    role: '학생',
    school: '간섭',
    rank: '학생, 간섭4서클(졸업반)',
    quote: '크큭... 이 지식의 끝에는 과연 뭐가 있을까...',
    mbti: 'INTJ',
    enneagram: '548',
    weaponOrMagic: '금기 탐구',
    imageUrl: getAssetUrl('ZN_A1.webp?v=0'),
    icon: '📖',
  },
  {
    id: 'ZO',
    name: '크리스티나 폰 에런',
    title: '선민의식',
    gender: '여',
    faction: '세오른 마법 아카데미',
    role: '학생',
    school: '영역',
    rank: '학생, 영역3서클(4학년)',
    quote: '천박한 자들은 당장 내 눈앞에서 꺼지세요.',
    mbti: 'ESTJ',
    enneagram: '836',
    weaponOrMagic: '선민의식',
    imageUrl: getAssetUrl('ZO_A1.webp?v=0'),
    icon: '📖',
  },
  {
    id: 'ZP',
    name: '클레오 우드',
    title: '호기심',
    gender: '여',
    faction: '세오른 마법 아카데미',
    role: '학생',
    school: '정령',
    rank: '학생, 정령2서클(2학년)',
    quote: '우와! 이거 터트리면 어떻게 될까? 해봐도 돼?',
    mbti: 'ENFP',
    enneagram: '749',
    weaponOrMagic: '호기심',
    imageUrl: getAssetUrl('ZP_A1.webp?v=0'),
    icon: '📖',
  },
  {
    id: 'ZQ',
    name: '페넬로페 라일락',
    title: '관심 요구',
    gender: '여',
    faction: '세오른 마법 아카데미',
    role: '학생',
    school: '원소',
    rank: '학생, 원소3서클(3학년)',
    quote: '나만 봐달란 말이야! 나 말고 다른 데 보지 마!',
    mbti: 'ESFP',
    enneagram: '478',
    weaponOrMagic: '관심 요구',
    imageUrl: getAssetUrl('ZQ_A1.webp?v=0'),
    icon: '📖',
  },
  {
    id: 'MJ',
    name: '아드리안 폰 크로스',
    title: '예절 준수',
    gender: '남',
    faction: '세오른 마법 아카데미',
    role: '학생',
    school: '정령',
    rank: '학생, 정령2서클(2학년)',
    quote: '마법은 고귀한 것다. 기품을 지켜.',
    mbti: 'ISTJ',
    enneagram: '136',
    weaponOrMagic: '규율 준수',
    imageUrl: getAssetUrl('MJ_A1.webp?v=0'),
    icon: '📖',
  },
  {
    id: 'ZH',
    name: '이자벨라 바인',
    title: '마법 연구',
    gender: '여',
    faction: '세오른 마법 아카데미',
    role: '교수',
    school: '원소',
    rank: '교수, 원소7서클',
    quote: '궁금한 것 있으면 교수님한테 언제든 물어봐~',
    mbti: 'ENFJ',
    enneagram: '279',
    weaponOrMagic: '마법 연구',
    imageUrl: getAssetUrl('ZH_A1.webp?v=0'),
    icon: '📖',
  },
  {
    id: 'ZI',
    name: '카멜리아 블랑',
    title: '원칙주의',
    gender: '여',
    faction: '세오른 마법 아카데미',
    role: '교수',
    school: '간섭',
    rank: '교수, 간섭6서클',
    quote: '..교칙 위반은 용서 안합니다.',
    mbti: 'ESTJ',
    enneagram: '136',
    weaponOrMagic: '원칙주의',
    imageUrl: getAssetUrl('ZI_A1.webp?v=0'),
    icon: '📖',
  },
  {
    id: 'ZJ',
    name: '타이라 로스',
    title: '실전 마법',
    gender: '여',
    faction: '세오른 마법 아카데미',
    role: '교수',
    school: '영역',
    rank: '교수, 영역7서클',
    quote: '책상머리에서 배운 마법이 실전에서 통할 거 같아?!',
    mbti: 'ENTP',
    enneagram: '783',
    weaponOrMagic: '실전 마법',
    imageUrl: getAssetUrl('ZJ_A1.webp?v=0'),
    icon: '📖',
  },
  {
    id: 'MI',
    name: '루시안 폰 테르미나',
    title: '지적 허영',
    gender: '남',
    faction: '세오른 마법 아카데미',
    role: '교수',
    school: '영역',
    rank: '교수, 영역7서클',
    quote: '내 영역에서는 날 아무도 못 이길걸?',
    mbti: 'INTJ',
    enneagram: '538',
    weaponOrMagic: '지적 허영',
    imageUrl: getAssetUrl('MI_A1.webp?v=0'),
    icon: '📖',
  },

  { id: 'unk1', name: '???', title: '알려지지 않은 간부', gender: '미상', faction: '검은 여명회', role: '미상', rank: '측정 불가', quote: '', mbti: '???', enneagram: '???', weaponOrMagic: '???', imageUrl: getAssetUrl('UNK1_A1.webp?v=0'), icon: '🦇' },
  { id: 'unk2', name: '???', title: '알려지지 않은 첩자', gender: '미상', faction: '검은 여명회', role: '미상', rank: '측정 불가', quote: '', mbti: '???', enneagram: '???', weaponOrMagic: '???', imageUrl: getAssetUrl('UNK2_A1.webp?v=0'), icon: '🦇' },
  { id: 'unk3', name: '???', title: '침묵의 수행자', gender: '미상', faction: '검은 여명회', role: '미상', rank: '측정 불가', quote: '', mbti: '???', enneagram: '???', weaponOrMagic: '???', imageUrl: getAssetUrl('UNK3_A1.webp?v=0'), icon: '🦇' },
  { id: 'unk4', name: '???', title: '미궁의 배신자', gender: '미상', faction: '검은 여명회', role: '미상', rank: '측정 불가', quote: '', mbti: '???', enneagram: '???', weaponOrMagic: '???', imageUrl: getAssetUrl('UNK4_A1.webp?v=0'), icon: '🦇' },
  { id: 'unk5', name: '???', title: '그림자 관찰자', gender: '미상', faction: '검은 여명회', role: '미상', rank: '측정 불가', quote: '', mbti: '???', enneagram: '???', weaponOrMagic: '???', imageUrl: getAssetUrl('UNK5_A1.webp?v=0'), icon: '🦇' }

];
